#Composing for production environment
version: "3.8"
services:
  nginx:
    ports:
      - "80:80"

  express-server:
    build:
      context: . #ref/location/context of Dockerfile
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
    command: node index.js