#Composing for development environment
version: "3.8"
services:
  express-server:
    build:
      context: . #ref/location/context of Dockerfile
      args:
        NODE_ENV: development
    volumes:
      - ./:/app:ro
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=Tamoziit
      - MONGO_PASSWORD=tamojitdas2605
      - SESSION_SECRET=secretsecret
    command: npm run dev

  mongo: #DB image
    environment:
      - MONGO_INITDB_ROOT_USERNAME=Tamoziit
      - MONGO_INITDB_ROOT_PASSWORD=tamojitdas2605